Draft: Add missing functions in primal
LLNL/axom pull request #1313
Opened 2024-04-08 21:22 UTC by adayton1

# Summary

- This PR is a feature
- It does the following:
  - Adds missing AXOM_HOST_DEVICE specifiers to several methods in Point, Segment, and Vector classes
  - Adds length_squared method to the Segment class
  - Adds cross, normalize, and unitize methods to the Vector class
  - Adds squared_distance operator

2024-04-08 22:22 UTC, kennyweiss requested changes
Thanks for adding these @adayton1 -- looks good to me, but I'd have a bit more confidence if there were a few unit tests, especially for the new `Vector::cross` implementation in 2D and 3D.

I'd also like to hear more about the need for both `Vector::normalize()` and `Vector::unitize()`

2024-04-08 22:22 UTC, kennyweiss commented on src/axom/primal/geometry/Vector.hpp
> +  void unitize();
Suggestion: Is there a good reason to have two functions that do the same thing? 
If not, my preference would be to only have `normalize()` (which is the conventional way to refer to this operation).

2024-04-08 22:22 UTC, kennyweiss commented on src/axom/primal/geometry/Vector.hpp
> +}
Should `Vector::unitVector()` be implemented in terms of this one?

Here's the current implementation:
https://github.com/LLNL/axom/blob/379db95ceed3ce8e90145993a0d9c33f8103f330/src/axom/primal/geometry/Vector.hpp#L489-L507

2024-04-08 22:22 UTC, kennyweiss commented on src/axom/primal/geometry/Vector.hpp
> +}
We might need to be careful about this one -- the current `cross_product` overloads are defined as:
* `cross_product(Vector3, Vector3) -> Vector3`
* `cross_product(Vector2, Vector2) -> Vector3`  // where the x- and y- components are 0

https://github.com/LLNL/axom/blob/379db95ceed3ce8e90145993a0d9c33f8103f330/src/axom/primal/geometry/Vector.hpp#L567-L586

2024-04-08 22:22 UTC, kennyweiss commented on src/axom/primal/geometry/Vector.hpp
>                                                        const T& z)
Side note (outside the scope of this PR):

The `make_vector` utility function was introduced before we had an initializer list constructor for a `primal::Vector`. I'm not sure if we still need the `make_vector` helper function.  (and similarly for `Point::make_point`)

2024-09-24 17:33 UTC, adayton1 commented
The portion of changes that are ready are being pulled into this merge request: https://github.com/LLNL/axom/pull/1422

2024-09-24 18:21 UTC, adayton1 commented
I'm going to pull out changes into different pull requests.

2024-09-24 18:21 UTC, closed without merging