Feature/sina/hdf5 output support
LLNL/axom pull request #1480
Opened 2024-12-20 00:09 UTC by doutriaux1

# Summary

- This PR is a feature
- It does the following (modify list as needed):
  - Adds the capacity to output sina files as hdf5 and opens the door for more formats in the future

2024-12-20 00:13 UTC, cyrush commented on src/axom/sina/core/Document.cpp
> +        conduit::Node relationship_nodes = asNode[RELATIONSHIPS_KEY];
this should be a ref to avoid a copy

2024-12-20 00:19 UTC, cyrush commented on src/axom/sina/core/Document.cpp
> +        relationshipsNode.append() = modifiedRelationshipsNode;
you could pass ref to append result into removeSlashes to avoid one extra copy.

2024-12-20 01:22 UTC, cyrush commented on src/spack
was this sub module add intended?

2024-12-21 00:49 UTC, bgunnar5 reviewed
Left some suggestions for you. Also wondering if the fortran changes are tested?

2024-12-21 00:49 UTC, bgunnar5 commented on src/axom/sina/core/Document.cpp
> +    }
Similar to `saveDocument` we might consider using a `switch` statement here as well.

2024-12-21 00:49 UTC, bgunnar5 commented on src/axom/sina/core/Document.hpp
> +}
Remove as this is a duplicate of the same function below (lines 245-254)

2024-12-21 00:49 UTC, bgunnar5 commented on src/axom/sina/docs/sphinx/tutorial.rst
> +the file.
"the output file" instead for clarity

2024-12-21 00:49 UTC, bgunnar5 commented on src/axom/sina/examples/sina_tutorial.cpp
> +  axom::sina::Document doc2 = axom::sina::loadDocument("my_output.json", axom::sina::Protocol::HDF5);
I think this should this be "my_output.hdf5" as the first argument to `loadDocument`

2025-01-24 22:44 UTC, gwaegner commented on src/axom/sina/core/Document.cpp
> +        relationshipsNode.append() = modifiedRelationshipsNode;
Copy removed

2025-01-24 22:45 UTC, gwaegner commented on src/spack
Submodule removed

2025-01-24 22:46 UTC, gwaegner commented on src/axom/sina/core/Document.cpp
> +void protocol_warn(std::string protocol, std::string const &name) {
Renamed and changed to const

2025-01-24 22:47 UTC, gwaegner commented on src/axom/sina/core/Document.cpp
> +}
Implemented as unordered map

2025-01-24 22:47 UTC, gwaegner commented on src/axom/sina/core/Document.cpp
> +                restoredKey.replace(pos, toReplace.length(), replacement);
Names fixed

2025-01-24 22:50 UTC, gwaegner commented on src/axom/sina/core/Document.cpp
> +        }
CreateFromNode updated to error out on primitives, set empty objects to empty lists, and iterate through lists to meet requirements

2025-01-24 22:52 UTC, gwaegner commented on src/axom/sina/core/Document.cpp
> +  }
This one can't be done due to switch statements not allowing variable instantiation with interferes with preexisting JSON code

2025-01-24 22:55 UTC, gwaegner commented on src/axom/sina/core/Document.cpp
> +    }
Changed to switch statement

2025-01-24 22:55 UTC, gwaegner commented on src/axom/sina/core/Document.hpp
> +}
Duplicate removed

2025-01-24 22:56 UTC, gwaegner commented on src/axom/sina/docs/sphinx/tutorial.rst
> +the file.
Updated

2025-01-24 22:56 UTC, gwaegner commented on src/axom/sina/examples/sina_tutorial.cpp
> +  axom::sina::Document doc2 = axom::sina::loadDocument("my_output.json", axom::sina::Protocol::HDF5);
Updated

2025-01-24 23:04 UTC, gwaegner commented on src/axom/sina/core/Document.cpp
> +        conduit::Node relationship_nodes = asNode[RELATIONSHIPS_KEY];
Removed as many copies as I could, this one underwent additional changes

2025-01-24 23:32 UTC, cyrush commented on src/axom/sina/core/Document.cpp
> +        relationshipsNode.append() = modifiedRelationshipsNode;
are the changes pushed, I  see:
```
removeSlashes(relationshipNode, modifiedRelationshipsNode);
        relationshipsNode.append() = modifiedRelationshipsNode;
```

however, I expect something like?
```
removeSlashes(relationshipNode, relationshipsNode.append());
```

2025-01-25 00:29 UTC, doutriaux1 commented on src/axom/sina/core/Document.cpp
> +        relationshipsNode.append() = modifiedRelationshipsNode;
@cyrush @gwaegner cannot push. I just pushed the changes.

2025-01-26 16:40 UTC, doutriaux1 commented
@gwaegner please take a look at the failures

2025-01-28 17:12 UTC, bmhan12 reviewed
The updated ReadTheDocs documentation for this PR can be previewed here: https://axom.readthedocs.io/en/feature-sina-hdf5_output_support/axom/sina/docs/sphinx/index.html

2025-01-28 17:12 UTC, bmhan12 commented on src/axom/sina/core/Document.hpp
> + * \param protocol the file type requested to save as, default = JSON
Maybe want to note here that HDF5 file type is also supported, or update `Document` class description.

2025-01-28 17:12 UTC, bmhan12 commented on src/axom/sina/core/Document.hpp
>   *
Should the class header description for `Document` be updated, generalized to include hdf5?

2025-01-28 17:14 UTC, bmhan12 commented on src/spack
Looks like the PR is trying to make unintended changes to submodules (blt, data, radiuss-spack-configs)

2025-01-29 03:47 UTC, kennyweiss requested changes
Thank you for the contribution and the improved tests and documentation!

Since hdf5 is an optional dependency for axom and for conduit, please ensure that this branch is tested against an Axom that is configured without `hdf5`. It is likely that this will require some appropriately placed `#ifdef` guards and/or error handling.

Also, it doesn't seem like this branch modifies the submodules, so I think something needs to be fixed in the way the commits were made.

I also highlighted some places where the might could be simplified using utilities in axom's core component. Please consider using these (but it's not required).

2025-01-29 03:47 UTC, kennyweiss commented on src/axom/sina/tests/sina_Document.cpp
> +  "\"object\": \"test_4\"}]}";
For improved readability, would it be possible to convert these to raw string literals?

2025-01-29 03:47 UTC, kennyweiss commented on src/axom/sina/tests/sina_Document.cpp
> +  saveDocument(document, tmpFile.getName(), Protocol::HDF5);
`hdf5` is an optional dependency for Axom. What happens if `HDF5` is not available? 

Should this be guarded w/ `#ifdef AXOM_USE_HDF5` ?

2025-01-29 03:47 UTC, kennyweiss commented on src/axom/sina/tests/sina_Document.cpp
> +  saveDocument(myDocument, "round_json.hdf5", Protocol::HDF5);
Note: `hdf5` might not always be available.

2025-01-29 03:47 UTC, kennyweiss commented on src/axom/sina/core/Document.cpp
> +  }
This might be streamlined with functions from our string utilities, e.g. `axom::utilties::string::endsWith()`, and or `axom::Path`.

See: 
* https://github.com/LLNL/axom/blob/develop/src/axom/core/utilities/StringUtilities.hpp
* https://github.com/LLNL/axom/blob/develop/src/axom/core/Path.hpp

Also, please use the SLIC macros, like `SLIC_INFO` and `SLIC_WARNING` instead of `cout`

2025-01-29 03:47 UTC, kennyweiss commented on src/axom/sina/core/Document.cpp
> +void removeSlashes(const conduit::Node &originalNode, conduit::Node &modifiedNode)
I think this could be streamlined via `axom::utilities::string::replaceAllInstances()`

2025-02-04 20:34 UTC, gwaegner commented on src/axom/sina/tests/sina_Document.cpp
> +  "\"object\": \"test_4\"}]}";
Converted to literals

2025-02-04 20:34 UTC, gwaegner commented on src/axom/sina/tests/sina_Document.cpp
> +  saveDocument(document, tmpFile.getName(), Protocol::HDF5);
ifdef guarding implemented throughout the code

2025-02-04 20:34 UTC, gwaegner commented on src/axom/sina/tests/sina_Document.cpp
> +  saveDocument(myDocument, "round_json.hdf5", Protocol::HDF5);
HDF5 tests are now guarded

2025-02-04 20:35 UTC, gwaegner commented on src/axom/sina/core/Document.cpp
> +  }
axom::Path used to steamline, error is no longer a cout

2025-02-04 20:35 UTC, gwaegner commented on src/axom/sina/core/Document.cpp
> +void removeSlashes(const conduit::Node &originalNode, conduit::Node &modifiedNode)
replaceAllInstances() utilitzed

2025-02-04 20:39 UTC, gwaegner commented on src/spack
Submodule changes came from develop merges, double checked for intentionality

2025-02-06 20:54 UTC, gwaegner commented on src/axom/sina/core/Document.hpp
> +   */
Documentation updated

2025-02-06 20:54 UTC, gwaegner commented on src/axom/sina/core/Document.hpp
> + * \param protocol the file type requested to save as, default = JSON
Documentation updated

2025-02-06 20:54 UTC, gwaegner commented on src/axom/sina/core/Document.hpp
>   *
Documentation updated

2025-02-19 04:12 UTC, kennyweiss commented
Note: I created a PR to fix some tests for Axom configs without `hdf5` (independent of this PR): https://github.com/LLNL/axom/pull/1504

2025-02-19 05:23 UTC, doutriaux1 commented
I've seen that. Thanks @kennyweiss . @gwaegner please take a look at Kenny's PR as well to see how he took care of things there.

2025-02-24 18:09 UTC, doutriaux1 commented
@kennyweiss it is showing some submodule changes, is that normal?

2025-02-28 01:32 UTC, gwaegner commented on src/axom/sina/core/Document.hpp
> +};
Protocol::HDF5 is now always defined to allow functions to fail at runtime for attempting HDF5 requests while it's missing by checking if a Vector containing supported file types contains the requested enum

2025-02-28 01:33 UTC, gwaegner commented on src/axom/sina/docs/sphinx/documents.rst
> +        axom::sina::Document myDocument = axom::sina::loadDocument("MySinaData.hdf5", axom::sina::Protocol::HDF5);
HDF5 is always defined so there shouldn't be a compilation error

2025-02-28 01:34 UTC, gwaegner commented on src/axom/sina/examples/sina_basic.cpp
> +#ifdef AXOM_USE_HDF5
Much appreciated!

2025-02-28 01:34 UTC, gwaegner commented on src/axom/sina/examples/sina_fortran.f
Fortran's HDF5 requirements are now effectively guarded

2025-02-28 01:35 UTC, gwaegner commented on src/axom/sina/core/Document.hpp
> +                      Protocol protocol = Protocol::JSON);
Supplying HDF5 with missing HDF5 support is now a runtime error

2025-02-28 01:40 UTC, gwaegner commented on src/axom/sina/core/Document.hpp
> + * \param protocol the type of file being loaded, default = JSON
Notes on when the function will throw a std::invalid_argument are now implemented

2025-02-28 01:42 UTC, gwaegner commented on src/axom/sina/core/Document.cpp
> +  }
The code will hit this else if a user attempts Protocol::HDF5 with no HDF5 support since the else if(Protocol::HDF5) case will not be loaded

2025-02-28 01:46 UTC, gwaegner commented on src/axom/sina/interface/sina_fortran_interface.cpp
> +  axom::sina::Protocol proto = static_cast<axom::sina::Protocol>(*protocol);
Calling write_sina_document_protocol_ will return an Invalid Argument error that requests you use a supported type, providing a list from a vector that can be updated as new file support is added.

2025-02-28 01:47 UTC, gwaegner commented on src/axom/sina/core/Document.cpp
> +    break;
the code will hit this else if a user attempts Protocol::HDF5 with no HDF5 support since the else if(Protocol::HDF5) case will not be loaded, the default has been updated to return an Invalid Argument error with a message that shows the supported types and requests you use one.

2025-03-05 17:54 UTC, gwaegner commented
All requested changes should be accounted for.  Is someone able to give this another look over?

2025-03-05 19:01 UTC, kennyweiss requested changes
Thanks @gwaegner for incorporating all the suggestions.

I added a few more relatively small comments.
My only remaining concern is about how sina is installed, which should be easy to remedy. @white238 -- would you mind looking at the CMake files?

Please also update the RELEASE_NOTES to add a note about the new HDF5 output support.

Also, when it's ready, this PR will have to be squashed merged due to the submodule changes in its history.

2025-03-06 17:17 UTC, gwaegner commented on src/axom/sina/docs/sphinx/hdf5_vs_json.rst
> +* Hierarchal structure leads to being 2.5x more size efficient and 5x faster at our largest
Updated.

2025-03-06 17:17 UTC, gwaegner commented on src/axom/sina/docs/sphinx/tutorial.rst
> +nothing. Alternatively, if you wish to save the document to an HDF5 file, you must set
Added a sentence about requiring axom configuration first before you try using Protocol HDF5

2025-03-06 17:19 UTC, gwaegner commented on src/axom/sina/examples/sina_tutorial.cpp
>    axom::sina::saveDocument(doc, "my_output.json");
Edited sina_basic to be an example of using Protocol::JSON explicitly, edited its comment to reference how an implicit use would still work.

2025-03-06 23:35 UTC, doutriaux1 commented on src/axom/sina/CMakeLists.txt
> +endif()
@kennyweiss yes at some point we should convert to shroud as a separate PR. But it's kind of "if it's ain't broken why fix it?" at the moment 😉

2025-03-07 19:48 UTC, gwaegner commented on src/axom/sina/CMakeLists.txt
> +  ELEMENTS interface/sina_fortran_interface.cpp interface/sina_fortran_interface.f.in)
Updated to remove .f.in's inclusion

2025-03-07 19:48 UTC, gwaegner commented on src/axom/sina/CMakeLists.txt
> +  configure_file(interface/sina_fortran_interface.f.in interface/sina_fortran_interface.f @ONLY)
.f file is now explicitly installed.

2025-03-07 19:59 UTC, gwaegner commented on src/axom/sina/core/Document.cpp
> +  }
Switch statements do not allow us to instantiate variables within cases which causes problems for the JSON case.  If we used a switch statement we would end up running auto asJson = document.toJson() even when saving as HDF5 or getting an unsupported protocol.

2025-03-17 17:13 UTC, doutriaux1 commented
> Thanks @gwaegner for incorporating all the suggestions.
> 
> I added a few more relatively small comments. My only remaining concern is about how sina is installed, which should be easy to remedy. @white238 -- would you mind looking at the CMake files?
> 
> Please also update the RELEASE_NOTES to add a note about the new HDF5 output support.
> 
> Also, when it's ready, this PR will have to be squashed merged due to the submodule changes in its history.

@kennyweiss and @white238 can we do this in another PR if you do not have time to look at it right now? I'd like this PR to be merged so we can open the next one. Thanks!

2025-03-17 19:42 UTC, white238 commented on src/axom/sina/CMakeLists.txt
> +  install(FILES ${CMAKE_CURRENT_BINARY_DIR}/interface/sina_fortran_interface.f
Are you sure this file needs to be installed? I could be wrong but I don't think there is a reason to install Fortran source files, just module files. We don't have any installed currently. @ltaylor16 could you weigh in given this isn't my strong suit?

2025-03-17 19:50 UTC, ltaylor16 commented on src/axom/sina/CMakeLists.txt
> +  install(FILES ${CMAKE_CURRENT_BINARY_DIR}/interface/sina_fortran_interface.f
correct, only the compiled module files need to be installed.

2025-03-18 01:18 UTC, kennyweiss commented on src/axom/sina/docs/sphinx/documents.rst
> +supported types instead as a runtime error.
Minor: It might be clearer to discuss an Axom _configuration_ with HDF5. I.e. Axom supports HDF5, but could be configures with or without HDF5 enabled.

Something like the following might be clearer:
```suggestion
When Axom is configured with HDF5 support, Sina's ``saveDocument()`` and ``loadDocument()`` functions support HDF5 assembly through the `Protocol::HDF5` argument.  The functions will throw a runtime error with the list of available types in Axom configurations without HDF5 support.
```

2025-03-18 01:20 UTC, kennyweiss commented on src/axom/sina/examples/sina_basic.cpp
> +  // if we wished, we could provide no third argument since saveDocument defaults to JSON.
Minor:
```suggestion
  // The third argument is optional and defaults to JSON.
```

2025-03-18 01:46 UTC, doutriaux1 commented
> Thanks @gwaegner -- A few more small fixes and this PR will be ready to merge.
> 
> As a reminder, this PR will have to be squash merged

Thanks @kennyweiss

2025-03-25 20:37 UTC, doutriaux1 commented
Thanks @gwaegner everything is GREEN! I believe all comments have been addressed. Are we good to merge this in? @kennyweiss @white238 are we good at this point?

2025-03-26 15:50 UTC, HaluskaR approved these changes
Looks great! Excellent cleanups.

2025-03-28 19:35 UTC, doutriaux1 commented
@kennyweiss @white238 @rhornung67 I believe @gwaegner addressed everything. Can one of you squash merge it in please?

2025-03-31 22:56 UTC, gwaegner commented
@kennyweiss @white238 Just wanted to make sure there isn't any more necessary prep before the squash merge, and this branch is the foundation for my next one MR.

2025-04-01 20:37 UTC, gwaegner commented
@kennyweiss @white238 @rhornung67 Just wanted to echo Charles' ping on if this branch can be squash merged or if there's anything I need to take care of first, as my next merge request builds off this

2025-04-02 16:07 UTC, white238 commented on src/axom/sina/CMakeLists.txt
> +endif()
```suggestion
endif()

```

2025-04-02 16:33 UTC, white238 commented on src/axom/sina/core/Document.cpp
> +      if(it.node().dtype().is_string() || it.node().dtype().is_number() ||
This could be more readable and possibly more efficent if you stored the type then checked instead of calling the same function again and again.

2025-04-02 16:37 UTC, white238 commented on src/axom/sina/core/Document.cpp
> +}  // namespace axom
```suggestion
}  // namespace axom

```

2025-04-02 16:38 UTC, white238 commented on src/axom/sina/docs/sphinx/documents.rst
> +conduit.
```suggestion
Conduit.
```

2025-04-02 16:42 UTC, white238 commented on src/axom/sina/docs/sphinx/hdf5_vs_json.rst
> +.. ## Copyright (c) 2017-2025, Lawrence Livermore National Security, LLC and
As far as I can tell this is not showing up in the Sphinx documentation. Also the "Records" page is a bad link.

2025-04-02 16:44 UTC, white238 commented on src/axom/sina/docs/sphinx/hdf5_vs_json.rst
> +.. ## Copyright (c) 2017-2025, Lawrence Livermore National Security, LLC and
![Uploading {56E28D8E-E43B-49E2-9D3C-3D49B0D4F49C}.png…]()

2025-04-02 16:44 UTC, white238 commented on src/axom/sina/docs/sphinx/hdf5_vs_json.rst
> +.. ## Copyright (c) 2017-2025, Lawrence Livermore National Security, LLC and
![{56E28D8E-E43B-49E2-9D3C-3D49B0D4F49C}](https://github.com/user-attachments/assets/afe4f320-a459-4535-9000-ca94d58f3400)

2025-04-02 16:47 UTC, white238 commented on src/axom/sina/docs/sphinx/hdf5_vs_json.rst
> +.. ## Copyright (c) 2017-2025, Lawrence Livermore National Security, LLC and
It is probably because of line 6 needing to be unique and also it needs to be added to the `toctree` probably here:

https://github.com/LLNL/axom/blob/bdab62055d715e25a9979f3ef443ad5cfbf98f2d/src/axom/sina/docs/sphinx/core_concepts.rst?plain=1#L24

2025-04-02 16:52 UTC, white238 commented on src/axom/sina/examples/CMakeLists.txt
> +endforeach()
```suggestion
endforeach()

```

2025-04-02 16:53 UTC, white238 commented on src/axom/sina/interface/sina_fortran_interface.f.in
> +end module hdf5_config
```suggestion
end module hdf5_config

```

2025-04-02 16:53 UTC, white238 commented on src/axom/sina/tests/config.py.in
> +AXOM_USE_HDF5 = @AXOM_USE_HDF5_PY@
```suggestion
AXOM_USE_HDF5 = @AXOM_USE_HDF5_PY@

```

2025-04-02 16:54 UTC, white238 commented on src/axom/sina/tests/sina_Document.cpp
> +}  // namespace axom
```suggestion
}  // namespace axom

```

2025-04-02 16:55 UTC, white238 commented on src/axom/sina/tests/test_fortran_integration.py
>      runner.run(suite)
```suggestion
    runner.run(suite)

```

2025-04-02 16:56 UTC, white238 commented
Some minor changes on my end then it is fine to be merged

2025-04-02 16:59 UTC, white238 requested changes
Fix docs and minor tweaks

2025-04-02 22:08 UTC, gwaegner commented on src/axom/sina/tests/test_fortran_integration.py
>      runner.run(suite)
Implemented.

2025-04-02 22:09 UTC, gwaegner commented on src/axom/sina/tests/sina_Document.cpp
> +}  // namespace axom
Implemented.

2025-04-02 22:09 UTC, gwaegner commented on src/axom/sina/tests/config.py.in
> +AXOM_USE_HDF5 = @AXOM_USE_HDF5_PY@
Implemented.

2025-04-02 22:09 UTC, gwaegner commented on src/axom/sina/interface/sina_fortran_interface.f.in
> +end module hdf5_config
Implemented.

2025-04-02 22:10 UTC, gwaegner commented on src/axom/sina/examples/CMakeLists.txt
> +endforeach()
Implemented.

2025-04-02 22:13 UTC, gwaegner commented on src/axom/sina/docs/sphinx/hdf5_vs_json.rst
> +.. ## Copyright (c) 2017-2025, Lawrence Livermore National Security, LLC and
HDF5_vs_JSON nested in the Documents page as a new toctree, broken links on the Documents page are fixed.

2025-04-02 22:13 UTC, gwaegner commented on src/axom/sina/docs/sphinx/documents.rst
> +conduit.
Fixed.

2025-04-02 22:14 UTC, gwaegner commented on src/axom/sina/core/Document.cpp
> +}  // namespace axom
Implemented.

2025-04-02 22:14 UTC, gwaegner commented on src/axom/sina/core/Document.cpp
> +      if(it.node().dtype().is_string() || it.node().dtype().is_number() ||
it.node().dtype() stored as an auto data_type that is now referenced instead of additional calls.

2025-04-02 22:15 UTC, gwaegner commented on src/axom/sina/CMakeLists.txt
> +endif()
Implemented.

2025-04-03 18:36 UTC, gwaegner commented on src/axom/sina/docs/sphinx/tutorial.rst
> +axom for HDF5 support then you can set saveDocument()'s optional Protocol parameter
I can look into adjusting this one for my Append MR, it will just need this one merged first.

2025-04-04 18:46 UTC, white238 approved these changes

2025-04-07 22:10 UTC, white238 commented
/style

2025-04-08 01:18 UTC, merged